server:
  # 端口
  port: 8080

spring:
  mail:
    #邮件服务器地址
    host: smtp.163.com
    #协议
    protocol: smtp
    #编码格式
    default-encoding: utf-8
    #授权码
    password: CRNHKBXGKWPLUEIA
    #发送者邮箱地址
    username: xzs13002741038@163.com
      #端口
    port: 25

  #rabbitmq配置
  rabbitmq:
    password: guest

    username: guest
    host: 127.0.0.1
#    port: 5672
    listener:
      simple:
        #开启手动确认
        acknowledge-mode: manual
  redis:
    #超时时间
    connect-timeout: 10000ms
    #服务器地址
    host: 127.0.0.1
    #服务器端口
    port: 6379
    #数据库
    database: 0
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大等待时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5


